[package]
name = "aq-ng"
version = "0.2.0"
authors = ["yetone <yetoneful@gmail.com>"]
edition = "2018"
license = "MIT / Apache-2.0"
homepage = "https://github.com/yetone/accessibility"
repository = "https://github.com/yetone/accessibility"
description = "Accessibility query"

[dependencies]
# Use workspace dependencies
core-foundation.workspace = true
structopt.workspace = true

# Internal dependency (which now uses objc2)
accessibility-ng = { version = "0.2.0", path = "../accessibility-ng" }