[package]
name = "accessibility-ng"
version = "0.2.0"
authors = ["yetone <yetoneful@gmail.com>"]
edition = "2018"
license = "MIT / Apache-2.0"
homepage = "https://github.com/yetone/accessibility"
repository = "https://github.com/yetone/accessibility"
description = "Bindings for macOS Accessibility services"

[dependencies]
# Using workspace dependencies 
core-foundation.workspace = true
core-graphics-types.workspace = true
thiserror.workspace = true

# Replace objc with objc2
objc2.workspace = true
objc2-foundation.workspace = true
objc2-app-kit.workspace = true

# Internal dependency with path
accessibility-sys-ng = { version = "0.2.0", path = "../accessibility-sys-ng" }

[package.metadata.docs.rs]
default-target = "x86_64-apple-darwin"