[package]
name = "accessibility-sys-ng"
version = "0.2.0"
authors = ["yetone <yetoneful@gmail.com>"]
edition = "2018"
license = "MIT / Apache-2.0"
homepage = "https://github.com/yetone/accessibility"
repository = "https://github.com/yetone/accessibility"
description = "Bindings for macOS Accessibility services"

[dependencies]
core-foundation-sys.workspace = true

[package.metadata.docs.rs]
default-target = "x86_64-apple-darwin"